/**
 * @vitest-environment jsdom
 */
import { fireEvent, render } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import { InjectorProviders } from "~/components/InjectorProviders";

import { SelectorVertical } from ".";

describe("packages/DatePickerMega/components/SelectorVertical", () => {
  it(`must change prev/next month`, async () => {
    const spyClickMay = vi.fn();
    const spyClickJul = vi.fn();
    const data = [
      {
        month: 0,
        isJanuary: true,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "January",
        isHoveredRange: false,
      },
      {
        month: 1,
        isJanuary: false,
        isFebruary: true,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "February",
        isHoveredRange: false,
      },
      {
        month: 2,
        isJanuary: false,
        isFebruary: false,
        isMarch: true,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "March",
        isHoveredRange: false,
      },
      {
        month: 3,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: true,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "April",
        isHoveredRange: false,
      },
      {
        month: 4,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: true,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "May",
        isHoveredRange: false,
        onClick: spyClickMay,
      },
      {
        month: 5,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: true,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: true,
        isDisabled: false,
        text: "June",
        isHoveredRange: false,
      },
      {
        month: 6,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: true,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "July",
        isHoveredRange: false,
        onClick: spyClickJul,
      },
      {
        month: 7,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: true,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "August",
        isHoveredRange: false,
      },
      {
        month: 8,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: true,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "September",
        isHoveredRange: false,
      },
      {
        month: 9,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: true,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "October",
        isHoveredRange: false,
      },
      {
        month: 10,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: true,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "November",
        isHoveredRange: false,
      },
      {
        month: 11,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: true,
        isSelected: false,
        isDisabled: false,
        text: "December",
        isHoveredRange: false,
      },
    ] as any;

    const { getByLabelText } = render(
      <InjectorProviders forTesting>
        <SelectorVertical data={data} currentIndex={5} />
      </InjectorProviders>
    );
    const nextButton = getByLabelText("next");
    fireEvent.click(nextButton);
    expect(spyClickJul).toBeCalled();

    const prevButton = getByLabelText("previous");
    fireEvent.click(prevButton);
    expect(spyClickMay).toBeCalled();
  });
  it(`must scroll prev/next month`, async () => {
    const spyClickJul = vi.fn();
    const data = [
      {
        month: 0,
        isJanuary: true,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "January",
        isHoveredRange: false,
      },
      {
        month: 1,
        isJanuary: false,
        isFebruary: true,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "February",
        isHoveredRange: false,
      },
      {
        month: 2,
        isJanuary: false,
        isFebruary: false,
        isMarch: true,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "March",
        isHoveredRange: false,
      },
      {
        month: 3,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: true,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "April",
        isHoveredRange: false,
      },
      {
        month: 4,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: true,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "May",
        isHoveredRange: false,
      },
      {
        month: 5,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: true,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: true,
        isDisabled: false,
        text: "June",
        isHoveredRange: false,
      },
      {
        month: 6,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: true,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "July",
        isHoveredRange: false,
        onClick: spyClickJul,
      },
      {
        month: 7,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: true,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "August",
        isHoveredRange: false,
      },
      {
        month: 8,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: true,
        isOctober: false,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "September",
        isHoveredRange: false,
      },
      {
        month: 9,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: true,
        isNovember: false,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "October",
        isHoveredRange: false,
      },
      {
        month: 10,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: true,
        isDecember: false,
        isSelected: false,
        isDisabled: false,
        text: "November",
        isHoveredRange: false,
      },
      {
        month: 11,
        isJanuary: false,
        isFebruary: false,
        isMarch: false,
        isApril: false,
        isMay: false,
        isJune: false,
        isJuly: false,
        isAugust: false,
        isSeptember: false,
        isOctober: false,
        isNovember: false,
        isDecember: true,
        isSelected: false,
        isDisabled: false,
        text: "December",
        isHoveredRange: false,
      },
    ] as any;

    const { getByTestId } = render(
      <InjectorProviders forTesting>
        <SelectorVertical
          data={data}
          itemsBefore={-1}
          itemsAfter={-1}
          currentIndex={5}
        />
      </InjectorProviders>
    );
    const nextButton = getByTestId("batata");
    fireEvent.wheel(nextButton, {});
    expect(spyClickJul).toBeCalled();
  });
});
